---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: headless
spec:
  imageRepositoryRef:
    name: headless
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web
spec:
  imageRepositoryRef:
    name: web
  policy:
    semver:
      range: '>=1.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: remark42
spec:
  imageRepositoryRef:
    name: remark42
  policy:
    semver:
      range: '>=1.13.1'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: curl
spec:
  imageRepositoryRef:
    name: curl
  policy:
    semver:
      range: '>=8.9.1'
