---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: headless
  namespace: harrytang-staging
spec:
  image: ghcr.io/harrytang/headless
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web
  namespace: harrytang-staging
spec:
  image: ghcr.io/harrytang/web
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: remark42
  namespace: harrytang-staging
spec:
  image: umputun/remark42
  interval: 1m0s
