apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: slack
spec:
  summary: harrytang-staging # will be replaced based on environment
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    # - kind: GitRepository
    #   name: '*'
    # - kind: HelmRepository
    #   name: '*'
    - kind: Kustomization
      name: '*'
