---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: harrytang-staging
spec:
  encryptedData:
    auth: AgAZHm8nlu6UuzIruO8qgA+/vdDsp588awMnlNwBupohWyAIYEJmQ0KnrJIVjqNAour6S8zZfyB5SdGaxKoG4MLBgEVL9U5H2emBNirqDz5N2TU3dA4iW2i/khOpZiTiV2fYCffEAwP5b0KLCHNTQupC1e+OkWh45VA77n9rXVwo2DXil10QYIkkTAq48KaQQYrhmFdWivn/5nY7LsFZPt/T/S2of2PmsD63MKRWJsBJCN6nZ/289978bKb4sPnRigtbxmhpSXFIpy9LeFK16KfsQcHnjrE5mi4f9Bta47MOaH29Gn8UvUYJDoSyvJQWWjPxWSJH3q4yk2w5L5/j62/x0+TIzoYsqOLu2f17pwIIB8geTFHQObKVtgU5dWFrRqOKIaWIEXMWztc3pl5fD0ZLsC1smFtK32wKPvlstnDTIx5aTytyt5JQfAOgpoTiOcVg38CSQfh7F26kJ80joWsY5no2kkpfzM6R4i/3sxkc2XeZp6NbyMKjskg7b8bPYnPRhD7fVDr3luFl2nBOHssKRGOHAJ0PkidRD1eyzEJmDIon2IGD/hwN/ZlXl4jbs9L+oW5FLrBtpqFMq0xul9gv80W2FULOfdQdy70bnByUP5trl5HunGuXOaOdHJBLjC5Ih2VjWcR60OhoC8M1vIodn8dK9sGISHhkW3dfO7r9kxdCrh1/X0qdd5TdUCHKq5TO3qp79YmnAqt97gW6t42DmVJZRseBfJ+7MKskGZtK1QtAg853h9pCB8xNKMWQvjU=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: harrytang-staging
