apiVersion: v1
kind: ConfigMap
metadata:
  name: microsoft-identity-config
  namespace: harrytang-prod
data:
  microsoft-identity-association.json: |
    {
      "associatedApplications": [
        {
          "applicationId": "38c696c1-f6d7-40eb-99a8-a98f4cdb1026"
        }
      ]
    }
