apiVersion: v1
kind: Service
metadata:
  name: wellknown-identity
  namespace: harrytang-prod
spec:
  selector:
    app: wellknown-identity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
