apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:v1.2.9 # {"$imagepolicy": "harrytang-prod:headless"}
