---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apple-key
  namespace: harrytang-prod
spec:
  encryptedData:
    apple.p8: AgBoA9AJ9ES6SWfEg9kDKjZp6QQdmRJcsEKSbLKmHkwe9F/KDyZjXHgL5baFByevjPK0k94T5lmzj8sH0l0u7RfDe4YAZv04MSsRTtVioh8huwNT7X9P9sdddHx1+aeH6pV8T+M5Ajp684LNQRTpGXVOTuPBKMMR6v8myAaKco0Yr6Z7FLX5bh6h4yP8Him1GvRfOMlpUbvgtJDeWhIIwSzHZZlAqae5zQFAB7MbnZ0cTA+GiAVIAOd6sovPdTX/qZU2JQKinIEXpwwVa18N/7Ro2ej6UNZN6KG/+zG3hRuyXBTf7m+H8qdmgMHMJKYA2yXld7ra33uWCsgVlzOpsxmdBhVDsVmNYCGczrlGB40SbJ/l9Q5GFyBnfHFUdH06ZTeevd1T9ilj4sJyHFuE1PhGeGxExFmw4dJX3ccNjL/HnXiy5Hi0pxcPw5ajA7JuTkOcGHWfUF11T6Ls5uP0A3J5tiq2Zzpl9mgHkbDa3MA21WMVA2joaXbsXizUDWEY/YLyU+UjVIc8OhdE3EcbIUmvC6Rld29/NHD4QECvnA2vrJ7msadZV47ccx+KWqyQ+jDdFJzUqwejVpOgSnR8eqwWSGt8wCxXPpfikLuko1VZ5/Z+wjrpSBCYIIFYLCW+rZwrQGv/GVe+B1MU21jDvPCRBZDKifQjI943awhcjFtNgknK2Ctp/Py4rtdgdvjFXpSaGAQfdvKd5vt39fw8in/FspDrGHYtzFp7VAXAcMZ6A0CM2a9FoNlYQZqGB/LOvcSepDieGj/ujOxcSKGjXt02hSZkA5XWKHQ04OeXcTnVib5/Df4wZYt/xXq6KQTePJYX+knFZv0bp7J8mXbC1kStSBlry0Jg7cdVVkdgsbgXrG6IGMp2SjomwLsyPwO02xTjTLNRBKWWrCvefCKrxzRq4rMeGCyPMg+EURGb50mUjvvyZydTMmH/X5hdHfMStyMDDXCIBnlwM/l9ijxx4had/do+P+ejOh5kWU+J/0f9uoGMn3VZliqjes0R5t9oIeu0DFOzER47fA+zVM0DS4ll/w==
  template:
    metadata:
      creationTimestamp: null
      name: apple-key
      namespace: harrytang-prod
