---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remark42
  namespace: harrytang-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remark42
  namespace: harrytang-prod
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app: remark42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remark42
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: harrytang-prod
      labels:
        app: remark42
    spec:
      containers:
        - name: remark42
          image: umputun/remark42:v1.14.0 # {"$imagepolicy": "harrytang-prod:remark42"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: remark42-env
            - configMapRef:
                name: remark42-env
          volumeMounts:
            - name: srvvar
              mountPath: /srv/var
            - name: email-templates-volume
              mountPath: /srv/email_confirmation_login.html.tmpl
              subPath: email_confirmation_login.html.tmpl
            - name: email-templates-volume
              mountPath: /srv/email_confirmation_subscription.html.tmpl
              subPath: email_confirmation_subscription.html.tmpl
            - name: email-templates-volume
              mountPath: /srv/email_reply.html.tmpl
              subPath: email_reply.html.tmpl
            - name: email-templates-volume
              mountPath: /srv/email_unsubscribe.html.tmpl
              subPath: email_unsubscribe.html.tmpl
            - name: email-templates-volume
              mountPath: /srv/error_response.html.tmpl
              subPath: error_response.html.tmpl
            - name: apple-key
              mountPath: /srv/var/apple.p8
              subPath: apple.p8
          securityContext:
            # readOnlyRootFilesystem: false
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
          resources:
            requests:
              cpu: '1m'
              memory: '50Mi'
            limits:
              cpu: '250m'
              memory: '100Mi'
      securityContext:
        fsGroup: 1001
      volumes:
        - name: srvvar
          persistentVolumeClaim:
            claimName: remark42
        - name: email-templates-volume
          configMap:
            name: email-templates
        - name: apple-key
          secret:
            secretName: apple-key
