apiVersion: v1
data:
  email_confirmation_login.html.tmpl: "<!DOCTYPE html>\n<html>\n<head>\n\t<meta name=\"viewport\"
    content=\"width=device-width\" />\n\t<meta http-equiv=\"Content-Type\" content=\"text/html;
    charset=UTF-8\" />\n</head>\n<body>\n<div style=\"text-align: center; font-family:
    Arial, sans-serif; font-size: 18px;\">\n\t<div style=\"font-family: Helvetica,
    Arial, sans-serif; font-size: 18px; width: 100%; max-width: 640px; margin: auto;\"><h1
    style=\"position: relative; color: #4fbbd6; margin-top: 0.2em; text-align: center;\"><img
    style=\"height: 48px; display: block; margin-left: auto; margin-right: auto;\"
    src=\"https://assets.harrytang.xyz/favicon.png\" alt=\"Harry Tang\" /></h1>\n\t<p
    style=\"position: relative; max-width: 20em; margin: 0 auto 1em auto; line-height:
    1.4em;\">Confirmation for <b>{{.User}}</b> on site <b>{{.Site}}</b></p>\n\t<div
    style=\"background-color: #eee; max-width: 20em; margin: 0 auto; border-radius:
    0.4em; padding: 0.5em;\">\n\t\t<p style=\"position: relative; margin: 0 0 0.5em
    0;\">TOKEN</p>\n\t\t<p style=\"position: relative; font-size: 0.7em; opacity:
    0.8;\"><i>Please copy and paste this text into “token” field on comments page
    to login</i></p>\n\t\t<p style=\"position: relative; font-family: monospace; background-color:
    #fff; margin: 0; padding: 0.5em; word-break: break-all; text-align: left; border-radius:
    0.2em; -webkit-user-select: all; user-select: all;\">{{.Token}}</p>\n\t</div>\n\t<p
    style=\"position: relative; margin-top: 2em; font-size: 0.8em; opacity: 0.8;\"><i>Sent
    to {{.Address}}</i></p>\n</div>\n</body>\n</html>"
  email_confirmation_subscription.html.tmpl: "<!DOCTYPE html>\n<html>\n<head>\n\t<meta
    name=\"viewport\" content=\"width=device-width\" />\n\t<meta http-equiv=\"Content-Type\"
    content=\"text/html; charset=UTF-8\" />\n</head>\n<body>\n\t<!-- Some of blocks
    on this page have color: #000 because GMail can wrap block in his own tags which
    can change text color -->\n\t<div style=\"text-align: center; font-family: Helvetica,
    Arial, sans-serif; font-size: 18px;\">\n\t\t<div style=\"font-family: Helvetica,
    Arial, sans-serif; font-size: 18px; width: 100%; max-width: 640px; margin: auto;\"><h1
    style=\"position: relative; color: #4fbbd6; margin-top: 0.2em; text-align: center;\"><img
    style=\"height: 48px; display: block; margin-left: auto; margin-right: auto;\"
    src=\"https://assets.harrytang.xyz/favicon.png\" alt=\"Harry Tang\" /></h1>\n\t\t<p
    style=\"position: relative; max-width: 20em; margin: 0 auto 1em auto; line-height:
    1.4em; color:#000!important;\">Confirmation for <b>{{.User}}</b> on site <b>{{.Site}}</b></p>\n\t\t{{-
    if .SubscribeURL}}\n\t\t<p style=\"position: relative; margin: 0 0 0.5em 0;color:#000!important;\"><a
    href=\"{{.SubscribeURL}}{{.Token}}\">Click here to subscribe to email notifications</a></p>\n\t\t<p
    style=\"position: relative; margin: 0 0 0.5em 0;color:#000!important;\">Alternatively,
    you can use code below for subscription.</p>\n\t\t{{- end }}\n\t\t<div style=\"background-color:
    #eee; max-width: 20em; margin: 0 auto; border-radius: 0.4em; padding: 0.5em;\">\n\t\t\t<p
    style=\"position: relative; margin: 0 0 0.5em 0;color:#000!important;\">TOKEN</p>\n\t\t\t<p
    style=\"position: relative; font-size: 0.7em; opacity: 0.8;\"><i style=\"color:#000!important;\">Please
    copy and paste this text into “token” field on comments page to confirm subscription</i></p>\n\t\t\t<p
    style=\"position: relative; font-family: monospace; background-color: #fff; margin:
    0; padding: 0.5em; word-break: break-all; text-align: left; border-radius: 0.2em;
    -webkit-user-select: all; user-select: all;\">{{.Token}}</p>\n\t\t</div>\n\t\t<p
    style=\"position: relative; margin-top: 2em; font-size: 0.8em; opacity: 0.8;\"><i
    style=\"color:#000!important;\">Sent to {{.Email}}</i></p>\n\t</div>\n</body>\n</html>"
  email_reply.html.tmpl: "<!DOCTYPE html>\n<html>\n<head>\n\t<meta name=\"viewport\"
    content=\"width=device-width\" />\n\t<meta http-equiv=\"Content-Type\" content=\"text/html;
    charset=UTF-8\" />\n\t<style type=\"text/css\">\n\t\timg {\n\t\t\tmax-width: 100%;\n\t\t\tmax-height:
    250px;\n\t\t\tmargin: 5px 0;\n\t\t\tdisplay: block;\n\t\t\tcolor: #000;\n\t\t}\n\t\ta
    {\n\t\t\ttext-decoration: none;\n\t\t\tcolor: #0aa;\n\t\t}\n\t\tp {\n\t\t\tmargin:
    0 0 12px;\n\t\t}\n\t\tblockquote {\n\t\t\tmargin: 10px 0;\n\t\t\tpadding: 12px
    12px 1px 12px;\n\t\t\tbackground: rgba(255,255,255,.5)\n\t\t}\n\t</style>\n</head>\n<!--
    Some of blocks on this page have color: #000 because GMail can wrap block in his
    own tags which can change text color -->\n<body>\n\t  <div style=\"font-family:
    Helvetica, Arial, sans-serif; font-size: 18px; width: 100%; max-width: 640px;
    margin: auto;\"><h1 style=\"position: relative; color: #4fbbd6; margin-top: 0.2em;
    text-align: center;\"><img style=\"height: 48px; display: block; margin-left:
    auto; margin-right: auto;\" src=\"https://assets.harrytang.xyz/favicon.png\" alt=\"Harry
    Tang\" /></h1>\n\t\t{{- if .ForAdmin}}\n\t\t<div style=\"font-size: 16px; text-align:
    center; margin-bottom: 10px; color:#000!important;\">New comment from {{.UserName}}
    on your site {{if .PostTitle}} to «{{.PostTitle}}»{{ end }}</div>\n\t\t{{- else
    }}\n\t\t<div style=\"font-size: 16px; text-align: center; margin-bottom: 10px;
    color:#000!important;\">New reply from {{.UserName}} on your comment{{if .PostTitle}}
    to «{{.PostTitle}}»{{ end }}</div>\n\t\t{{- end }}\n\t\t<div style=\"background-color:
    #eee; padding: 15px 20px 20px 20px; border-radius: 3px;\">\n\t\t\t{{- if .ParentCommentText}}\n\t\t\t\t<div
    style=\"margin-bottom: 12px; line-height: 24px; word-break: break-all;\">\n\t\t\t\t\t<img
    src=\"{{.ParentUserPicture}}\" style=\"width: 24px; height: 24px; display: inline-block;
    vertical-align: middle; margin: 0 8px 0 0; border-radius: 3px; background-color:
    #ccc;\"/>\n\t\t\t\t\t<span style=\"font-size: 14px; font-weight: bold; color:
    #777\">{{.ParentUserName}}</span>\n\t\t\t\t\t<span style=\"color: #999; font-size:
    14px; margin: 0 8px;\">{{.ParentCommentDate.Format \"02.01.2006 at 15:04\"}}</span>\n\t\t\t\t\t<a
    href=\"{{.ParentCommentLink}}\" style=\"color: #0aa; font-size: 14px;\"><b>Show</b></a>\n\t\t\t\t</div>\n\t\t\t\t<div
    style=\"font-size: 14px; color:#333!important; padding: 0 14px 0 2px; border-radius:
    3px; line-height: 1.4;\">{{.ParentCommentText}}</div>\n\t\t\t{{- end }}\n\t\t\t<div
    style=\"padding-left: 20px; border-left: 1px dotted rgba(0,0,0,0.15); margin-top:
    15px; padding-top: 5px;\">\n\t\t\t\t<div style=\"margin-bottom: 12px; line-height:
    24px;word-break: break-all;\">\n\t\t\t\t\t<img src=\"{{.UserPicture}}\" style=\"width:
    24px; height: 24px; display:inline-block; vertical-align:middle; margin: 0 8px
    0 0; border-radius: 3px; background-color: #ccc;\"/>\n\t\t\t\t\t<span style=\"font-size:
    14px; font-weight: bold; color: #777\">{{.UserName}}</span>\n\t\t\t\t\t<span style=\"color:
    #999; font-size: 14px; margin: 0 8px;\">{{.CommentDate.Format \"02.01.2006 at
    15:04\"}}</span>\n\t\t\t\t\t<a href=\"{{.CommentLink}}\" style=\"color: #0aa;
    font-size: 14px;\"><b>Reply</b></a>\n\t\t\t\t</div>\n\t\t\t\t<div style=\"font-size:
    16px; background-color: #fff; color:#000!important; padding: 14px 14px 2px 14px;
    border-radius: 3px; line-height: 1.4;\">{{.CommentText}}</div>\n\t\t\t</div>\n\t\t</div>\n\t\t<div
    style=\"text-align: center; font-size: 14px; margin-top: 32px;\">\n\t\t\t<i style=\"color:
    #000!important;\">Sent to <a style=\"color:inherit; text-decoration: none\" href=\"mailto:{{.Email}}\">{{.Email}}</a>{{if
    not .ForAdmin}} for {{.ParentUserName}}{{ end }}</i>\n\t\t\t<div style=\"width:
    150px; border-top: 1px solid rgba(0, 0, 0, 0.15); padding-top: 15px; margin: 15px
    auto 0;\"></div>\n\t\t\t{{- if .UnsubscribeLink}}\n\t\t\t<a style=\"color: #0aa;\"
    href=\"{{.UnsubscribeLink}}\">Unsubscribe</a>\n\t\t\t{{- end }}\n\t\t\t<!-- This
    is hack for remove collapser in Gmail which can collapse end of the message -->\n\t\t\t<div
    style=\"opacity: 0;\">[{{.CommentDate.Format \"02.01.2006 at 15:04\"}}]</div>\n\t\t</div>\n\t</div>\n</body>\n</html>"
  email_unsubscribe.html.tmpl: "<!DOCTYPE html>\n<html>\n<head>\n\t\t<meta name=\"viewport\"
    content=\"width=device-width\"/>\n\t\t<meta http-equiv=\"Content-Type\" content=\"text/html;
    charset=UTF-8\"/>\n</head>\n<body>\n<div style=\"text-align: center; font-family:
    Arial, sans-serif; font-size: 18px;\">\n\t<div style=\"font-family: Helvetica,
    Arial, sans-serif; font-size: 18px; width: 100%; max-width: 640px; margin: auto;\"><h1
    style=\"position: relative; color: #4fbbd6; margin-top: 0.2em; text-align: center;\"><img
    style=\"height: 48px; display: block; margin-left: auto; margin-right: auto;\"
    src=\"https://assets.harrytang.xyz/favicon.png\" alt=\"Harry Tang\" /></h1>\n\t<p
    style=\"position: relative; max-width: 20em; margin: 0 auto 1em auto; line-height:
    1.4em;\">Successfully unsubscribed</p>\n</div>\n</body>\n</html>"
  error_response.html.tmpl: "<!DOCTYPE html>\n<html>\n<head>\n\t\t<meta name=\"viewport\"
    content=\"width=device-width\"/>\n\t\t<meta http-equiv=\"Content-Type\" content=\"text/html;
    charset=UTF-8\"/>\n</head>\n<body>\n<div style=\"text-align: center; font-family:
    Arial, sans-serif; font-size: 18px;\">\n\t<div style=\"font-family: Helvetica,
    Arial, sans-serif; font-size: 18px; width: 100%; max-width: 640px; margin: auto;\"><h1
    style=\"position: relative; color: #4fbbd6; margin-top: 0.2em; text-align: center;\"><img
    style=\"height: 48px; display: block; margin-left: auto; margin-right: auto;\"
    src=\"https://assets.harrytang.xyz/favicon.png\" alt=\"Harry Tang\" /></h1>\n\t<p
    style=\"position: relative; max-width: 20em; margin: 0 auto 1em auto; line-height:
    1.4em;\">{{.Error}}: {{.Details}}.</p>\n</div>\n</body>\n</html>"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: email-templates
  namespace: harrytang-staging
