apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:main-c8c1fe9-1787168614 # {"$imagepolicy": "harrytang-staging:headless"}
