apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:main-78ef9b1-1774781196 # {"$imagepolicy": "harrytang-staging:headless"}
