apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:main-fc36cdc-1765132021 # {"$imagepolicy": "harrytang-staging:headless"}
