apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:main-8940ae1-1767074690 # {"$imagepolicy": "harrytang-staging:headless"}
