apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:main-0393e6b-1765134535 # {"$imagepolicy": "harrytang-staging:headless"}
