apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless
spec:
  template:
    spec:
      containers:
        - name: headless
          image: ghcr.io/harrytang/headless:main-b745ae4-1778996535 # {"$imagepolicy": "harrytang-staging:headless"}
