apiVersion: apps/v1
kind: Deployment
metadata:
  name: headless-depl
  namespace: harrytang-staging
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app: headless-depl
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headless-depl
      version: v1
  template:
    metadata:
      labels:
        app: headless-depl
        version: v1
    spec:
      containers:
        - name: init
          ports:
            - containerPort: 1337
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          image: ghcr.io/harrytang/headless:main-e4f7ee2-1736687191 # {"$imagepolicy": "harrytang-staging:headless"}
          command: ['/bin/sh', '-c']
          args:
            - |
              echo "Building admin panel..."
              npm run build
              echo "Admin panel built"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: headless-env
            - configMapRef:
                name: headless-env
        - name: headless
          ports:
            - containerPort: 1337
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          image: ghcr.io/harrytang/headless:main-e4f7ee2-1736687191 # {"$imagepolicy": "harrytang-staging:headless"}
          imagePullPolicy: Always
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
          envFrom:
            - secretRef:
                name: headless-env
            - configMapRef:
                name: headless-env
