---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: headless
  namespace: harrytang-prod
spec:
  image: ghcr.io/harrytang/headless
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web
  namespace: harrytang-prod
spec:
  image: ghcr.io/harrytang/web
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: remark42
  namespace: harrytang-prod
spec:
  image: umputun/remark42
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: curl
  namespace: harrytang-prod
spec:
  image: curlimages/curl
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: uptime-kuma
  namespace: harrytang-prod
spec:
  image: louislam/uptime-kuma
  interval: 1m0s
