apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/harrytang/web:main-585a8c2-1764734249 # {"$imagepolicy": "harrytang-staging:web"}
