apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      initContainers:
        - name: next-data
          image: ghcr.io/harrytang/web:main-8cdcfad-1765032636 # {"$imagepolicy": "harrytang-staging:web"}
      containers:
        - name: web
          image: ghcr.io/harrytang/web:main-8cdcfad-1765032636 # {"$imagepolicy": "harrytang-staging:web"}
