---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-https
spec:
  parentRefs:
    - name: harrytang
      namespace: gateway
      sectionName: https
  hostnames:
    - harrytang.xyz