apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      initContainers:
        - name: next-data
          image: ghcr.io/harrytang/web:v1.22.5 # {"$imagepolicy": "harrytang-prod:web"}    
      containers:
        - name: web
          image: ghcr.io/harrytang/web:v1.22.5 # {"$imagepolicy": "harrytang-prod:web"}
