apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/harrytang/web:v1.22.2 # {"$imagepolicy": "harrytang-prod:web"}
