apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: harrytang-staging
spec:
  interval: 24h
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: dragonfly
    namespace: harrytang-staging
  values:
    replicaCount: 3
    storage:
      enabled: true
      requests: 128Mi
