---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: headless
spec:
  imageRepositoryRef:
    name: headless
  filterTags: # will be replaced based on environment
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: web
spec:
  imageRepositoryRef:
    name: web
  filterTags: # will be replaced based on environment
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: remark42
spec:
  imageRepositoryRef:
    name: remark42
  policy:
    semver:
      range: '>=1.13.1'
